### ISSUE TITLE
Update for 11.0.0

### ISSUE THREAD

**Issue by b-morgan** [rbgdevx/dynamic-movement-speed#1]
I don't like to check "Load Out of Date Addons" just after Blizzard does a major expansion. Can we please get an updated version for The World Within (11.0.0)?

**Comment by rbgdevx** [comment]
yes! sorry, i've been so busy with my main addon.

I'm also going to add in dragon riding support when i do this, ~probably will have this by end of the week into the weekend~ Soon™️.

**Comment by rbgdevx** [comment]
updated! and added dragon riding support!
